name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    name: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run test:mutate
      - name: Load npm token
        id: load_secrets
        uses: 1password/load-secrets-action@v4
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: op://Github Secrets/NPM_TOKEN/credential
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ steps.load_secrets.outputs.NPM_TOKEN }}
